name: Hermes
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - boltons=23.0.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=3.2.0
  - colorama=0.4.6
  - conda=23.7.4
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.11.0
  - cryptography=41.0.4
  - cudatoolkit=11.8.0
  - fmt=10.1.1
  - icu=73.2
  - idna=3.4
  - intel-openmp=2021.4.0
  - jsonpatch=1.32
  - jsonpointer=2.4
  - keyutils=1.6.1
  - krb5=1.20.1
  - ld_impl_linux-64=2.38
  - libarchive=3.6.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.2.1
  - libedit=3.1.20191231
  - libev=4.33
  - libfaiss=1.7.4
  - libfaiss-avx2=1.7.4
  - libffi=3.4.4
  - libgcc-ng=13.1.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - liblapack=3.9.0
  - libmamba=1.5.1
  - libmambapy=1.5.1
  - libnghttp2=1.52.0
  - libopenblas=0.3.21
  - libsolv=0.7.24
  - libssh2=1.10.0
  - libstdcxx-ng=13.1.0
  - libuuid=1.41.5
  - libxml2=2.10.4
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - mamba=1.5.1
  - mkl=2021.4.0
  - ncurses=6.4
  - openssl=3.1.3
  - packaging=23.1
  - pcre2=10.42
  - pip=23.2.1
  - pluggy=1.3.0
  - pybind11-abi=4
  - pycosat=0.6.4
  - pycparser=2.21
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.10.12
  - python_abi=3.10
  - readline=8.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - ruamel.yaml=0.17.32
  - ruamel.yaml.clib=0.2.7
  - sqlite=3.41.2
  - tk=8.6.12
  - toolz=0.12.0
  - tqdm=4.66.1
  - xz=5.4.2
  - yaml-cpp=0.7.0
  - zlib=1.2.13
  - zstandard=0.22.0
  - zstd=1.5.5
  - pip:
      - accelerate==1.4.0
      - aiohttp==3.8.5
      - aiosignal==1.3.1
      - albumentations==1.3.1
      - aniso8601==9.0.1
      - anyio==4.0.0
      - arrow-json==0.9.0
      - asttokens==2.4.1
      - async-timeout==4.0.3
      - attrs==23.1.0
      - av==14.2.0
      - backcall==0.2.0
      - bitsandbytes==0.41.1
      - blessed==1.20.0
      - blinker==1.6.2
      - braceexpand==0.1.7
      - cachetools==5.5.0
      - certifi==2023.7.22
      - chardet==5.2.0
      - click==8.1.7
      - cmake==3.27.4.1
      - comm==0.1.4
      - contourpy==1.3.1
      - cycler==0.12.1
      - dataclasses==0.6
      - datasets==2.14.6
      - debugpy==1.8.0
      - decorator==5.1.1
      - diffusers==0.21.2
      - dill==0.3.7
      - distro==1.8.0
      - docker-pycreds==0.4.0
      - exceptiongroup==1.1.3
      - executing==2.0.0
      - exifread-nocycle==3.0.1
      - fastapi==0.100.1
      - filelock==3.12.3
      - fire==0.4.0
      - flask==2.3.3
      - flask-cors==3.0.10
      - flask-restful==0.3.10
      - fonttools==4.55.3
      - frozenlist==1.4.0
      - fsspec==2023.10.0
      - ftfy==6.1.1
      - gitdb==4.0.10
      - gitpython==3.1.36
      - google-ai-generativelanguage==0.6.10
      - google-api-core==2.24.0
      - google-api-python-client==2.158.0
      - google-auth==2.37.0
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.8.3
      - googleapis-common-protos==1.66.0
      - grpcio==1.69.0
      - grpcio-status==1.69.0
      - h11==0.14.0
      - h2==3.2.0
      - h5py==3.9.0
      - hpack==3.0.0
      - hstspreload==2023.1.1
      - httpcore==1.0.2
      - httplib2==0.22.0
      - httpx==0.25.2
      - huggingface-hub==0.29.1
      - hyperframe==5.2.0
      - imageio==2.31.3
      - importlib-metadata==6.8.0
      - inquirer==3.1.3
      - ipykernel==6.26.0
      - ipython==8.16.1
      - itsdangerous==2.1.2
      - jedi==0.19.1
      - jinja2==3.1.2
      - jiter==0.8.2
      - joblib==1.3.2
      - jupyter-client==8.5.0
      - jupyter-core==5.4.0
      - kiwisolver==1.4.8
      - lazy-loader==0.3
      - lit==16.0.6
      - markupsafe==2.1.3
      - matplotlib==3.10.0
      - matplotlib-inline==0.1.6
      - mpmath==1.3.0
      - multidict==6.0.4
      - multilingual-clip==1.0.10
      - multiprocess==0.70.15
      - nest-asyncio==1.5.8
      - networkx==3.1
      - nltk==3.8.1
      - numpy==1.24.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu11==11.7.91
      - nvidia-nvtx-cu12==12.4.127
      - openai==1.59.6
      - opencv-python-headless==4.8.0.76
      - opentsne==1.0.0
      - pandas==2.2.3
      - parso==0.8.3
      - pathos==0.3.1
      - pathtools==0.1.2
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==10.0.0
      - platformdirs==3.11.0
      - pox==0.3.3
      - ppft==1.7.6.7
      - prometheus-client==0.17.1
      - promise==2.3
      - prompt-toolkit==3.0.39
      - proto-plus==1.25.0
      - protobuf==3.20.1
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyarrow==18.1.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pydantic==1.10.12
      - pygments==2.16.1
      - pyparsing==3.2.1
      - python-dateutil==2.8.2
      - python-editor==1.0.4
      - pytz==2023.3
      - pywavelets==1.4.1
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - qudida==0.0.4
      - qwen-vl-utils==0.0.10
      - readchar==4.0.5
      - regex==2023.8.8
      - requests==2.31.0
      - rfc3986==1.5.0
      - rsa==4.9
      - safetensors==0.5.2
      - scikit-image==0.21.0
      - scikit-learn==1.3.0
      - scipy==1.9.1
      - seaborn==0.13.2
      - sentencepiece==0.1.99
      - sentry-sdk==1.31.0
      - setproctitle==1.3.2
      - setuptools==68.2.1
      - shortuuid==1.0.11
      - six==1.16.0
      - smmap==5.0.0
      - sniffio==1.3.0
      - stack-data==0.6.3
      - starlette==0.27.0
      - sympy==1.13.1
      - termcolor==2.3.0
      - text-generation==0.6.0
      - threadpoolctl==3.2.0
      - tifffile==2023.8.30
      - timm==0.9.7
      - tokenizers==0.21.0
      - tomli==2.0.1
      - torch==2.6.0
      - torchvision==0.14.1
      - tornado==6.3.3
      - traitlets==5.12.0
      - transformers==4.49.0
      - triton==3.2.0
      - typing-extensions==4.12.2
      - tzdata==2023.3
      - uritemplate==4.1.1
      - urllib3==2.0.7
      - uvicorn==0.23.2
      - wandb==0.12.21
      - wcwidth==0.2.6
      - webdataset==0.2.48
      - websockets==11.0.3
      - werkzeug==2.3.7
      - wheel==0.41.2
      - xxhash==3.3.0
      - yarl==1.9.2
      - zeno-client==0.1.12
      - zeno-sliceline==0.0.1
      - zenoml==0.6.4
      - zipp==3.17.0
